### ISSUE TITLE
Can it support overleaf?

### ISSUE THREAD

**Issue by hbsun2113** [CasperVector/pkuthss#28]
Thanks for your contribution. But now, it cannot work on overleaf. I wonder whether this template can support overleaf?

**Comment by CasperVector** [comment]
I do not use overleaf, and am not familiar with it, so I cannot comment on it.

**Comment by liantze** [comment]
（我是Overleaf的工作人员，今天找资料时刚好路过这儿了）

_(I'm a support personnel at Overleaf; and came across this page today while looking for some info.)_


ctex-fontset-pkuthss.def指定了使用SimSun, SimHei等微软的商用字体。Overleaf伺服器的系统是Ubuntu，没有安装SimSun, Simkai等字体，因此不能编译通过。

_ctex-fontset-pkuthss.def uses SimSun, SimHei etc, but these are Microsoft commercial fonts, and therefore not installed on Overleaf's servers (we run Ubuntu Linux)._


最快的解决办法是去掉ctexopts.cfg，不调用ctex-fontset-pkuthss.def，让系统用默认的Fandol（比较丑我知道……）

_The easiest solutions is to remove ctexopts.cfg from your Overleaf project, so that it won't load the font definitions in ctex-fontset-pkuthss.def. The compiler will then use the default Fandol fontset (admittedly it's not such a great font, both on aesthetics and on glyph coverage...)_


要自行重定义 ctex-fontset-pkuthss.def 也行，可参考https://www.overleaf.com/learn/latex/Questions/What_OTF/TTF_fonts_are_supported_via_fontspec%3F#Chinese
但是实在没有开源的隶书、幼圆中文简体字体库，楷书体也只有文鼎 Arphic 的。甚惆怅。

_Another solution is to re-write ctex-fontset-pkuthss.def so that it uses fonts that *are* available on Overleaf; list [here](https://www.overleaf.com/learn/latex/Questions/What_OTF/TTF_fonts_are_supported_via_fontspec%3F#Chinese). But then again there aren't any open-source 隶书 and 幼圆 typefaces for Simplified Chinese; and even for 楷书 there are only offerings from Arphic._

**Comment by LongruiDong** [comment]
> （我是Overleaf的工作人员，今天找资料时刚好路过这儿了）
> 
> _(I'm a support personnel at Overleaf; and came across this page today while looking for some info.)_
> 
> ctex-fontset-pkuthss.def指定了使用SimSun, SimHei等微软的商用字体。Overleaf伺服器的系统是Ubuntu，没有安装SimSun, Simkai等字体，因此不能编译通过。
> 
> _ctex-fontset-pkuthss.def uses SimSun, SimHei etc, but these are Microsoft commercial fonts, and therefore not installed on Overleaf's servers (we run Ubuntu Linux)._
> 
> 最快的解决办法是去掉ctexopts.cfg，不调用ctex-fontset-pkuthss.def，让系统用默认的Fandol（比较丑我知道……）
> 
> _The easiest solutions is to remove ctexopts.cfg from your Overleaf project, so that it won't load the font definitions in ctex-fontset-pkuthss.def. The compiler will then use the default Fandol fontset (admittedly it's not such a great font, both on aesthetics and on glyph coverage...)_
> 
> 要自行重定义 ctex-fontset-pkuthss.def 也行，可参考https://www.overleaf.com/learn/latex/Questions/What_OTF/TTF_fonts_are_supported_via_fontspec%3F#Chinese 但是实在没有开源的隶书、幼圆中文简体字体库，楷书体也只有文鼎 Arphic 的。甚惆怅。
> 
> _Another solution is to re-write ctex-fontset-pkuthss.def so that it uses fonts that _are_ available on Overleaf; list [here](https://www.overleaf.com/learn/latex/Questions/What_OTF/TTF_fonts_are_supported_via_fontspec%3F#Chinese). But then again there aren't any open-source 隶书 and 幼圆 typefaces for Simplified Chinese; and even for 楷书 there are only offerings from Arphic._

你好 我在overleaf中删除了ctexopts.cfg文件，但还是出现同样的错误，是我没理解对吗？
