### ISSUE TITLE
如何更改页眉内容

### ISSUE THREAD

**Issue by Xiang-tao** [CasperVector/pkuthss#47]
请问下如何把第一章改成阿拉伯数字1呢？当然后面的第二章等依次都改成阿拉伯数字，谢谢啦

**Comment by CasperVector** [comment]
见 `texdoc ctex` 第 7.1 节（“编号相关”）。

**Comment by Xiang-tao** [comment]
> 见 `texdoc ctex` 第 7.1 节（“编号相关”）。

谢谢啦，成功了

**Comment by abbagarba** [comment]
请，我想寻求有关如何解决此问题的帮助。我一直在尝试修复它，但我无法找到解决方案。我的计算机科学系给了我你的联系电子邮件，我请求你的帮助，如果你能修复它或指导我如何修复它

I use this templet via overleaf. https://github.com/CasperVector/pkuthss

Please, I would like to ask for help on how to fix this issue. I have been trying to fix it but I could not get the solution. My department of computer science gave me your contact email and I am asking you for help if you can fix it or guide me on how to fix it. 

For example I was asked to change this words to English:
例如，我被要求把这些单词改成英语;

![image](https://user-images.githubusercontent.com/15909726/169387508-7dca9105-1186-4b52-b65c-b56609ee7f13.png)
![image](https://user-images.githubusercontent.com/15909726/169387724-d2e72a2f-99c6-459c-a9be-5745ac562446.png)
![image](https://user-images.githubusercontent.com/15909726/169388164-7a14baa8-b912-4001-8e8b-f245b617eca3.png)

章节号以中文出现。我试着把它改成英语，但我做不到；我浏览了一些文件，比如pkuths。cls，PKUTSS-utf8。def，主。tex等等，并尝试添加一些包，但仍然没有成功。我在文件中找不到文本，因此无法更改或编辑它。

如果你能为我提供任何帮助，请

Chapter numbers appeared in Chinese. I tried to change it to English, but I couldn't; I looked through some of the files, such as pkuthss.cls, pkuthss-utf8.def, main.tex, and so on, and tried to add some packages, but it still didn't work.I could not find the text in the files so that I could change or edit it. 

Please, if there is any assistance you could offer me. 
Thanks

**Comment by CasperVector** [comment]
You may consider trying https://github.com/CasperVector/pkuthss/blob/master/doc/readme/pkuthss-english.patch

**Comment by abbagarba** [comment]
Thank you very much @CasperVector so how can I make these changes to my current overleaf? Could you help to guide me?
Thank you once again.

**Comment by CasperVector** [comment]
I am not familiar with overleaf; you may need to contact the person who created your template.
Alternatively, as it seems that you can directly modify the template files (including `pkuthss.cls`), you can also try applying the changes in the patch file manually.

**Comment by CasperVector** [comment]
The mailbox can be found from the commit logs, accessible with the `git log` command.

**Comment by abbagarba** [comment]
Thank you very much. I have sent you an email. via Caspr...(at)googlemail.com
